[tools]
"npm:@anthropic-ai/claude-code" = "2.0.33"
"pipx:csvkit" = "2.1.0"
"pipx:tldr" = "3.4.3"
"cargo:zellij" = "0.43.1"
# imagemagick = "7.1.2-5"
age = "1.2.1"
aws = "2.31.29"
aws-vault = "7.2.0"
azure-cli = "2.79.0"
dagger = "0.19.4"
databricks-cli = "0.275.0"
doctl = "1.146.0"
fzf = "0.66.1"
go = "1.25.3"
golang = "1.24.5"
k9s = "0.50.16"
lua = "5.4.8"
node = "25.1.0"
poetry = "2.2.1"
python = "3.14.0"
rust = "1.91"
sops = "3.11.0"
sqlite = "3.51.0"
starship = "1.24.0"
terraform = "1.13.5"
usage = "2.6.0"
uv = "0.9.7"
yarn = "4.10.3"
yq = "4.48.1"

[settings]
idiomatic_version_file_enable_tools = [
    "go",
    "node",
    "python",
    "terraform",
    "yarn",
]
lockfile = true
experimental = true
