[tools]
"npm:@anthropic-ai/claude-code" = "2.1.17"
"npm:@github/copilot" = "0.0.393"
"npm:opencode-ai" = "1.1.34"
"npm:tree-sitter-cli" = "0.26.3"
"pipx:csvkit" = "2.2.0"
"pipx:tldr" = "3.4.3"
# "cargo:zellij" = "0.43.1"
# btop = "1.4.6"             #WARN: Unsupported on mac!
# imagemagick = "7.1.2-5"
age = "1.3.1"
ansible = "13.2.0"
aws-vault = "7.2.0"
awscli = { version = "2.33.5", symlink_bins = "true" }
azure-cli = "2.82.0"
bat = "0.26.1"                                         # CLI cat alternative with highlights https://github.com/sharkdp/bat
buf = "1.64.0"
dagger = "0.19.10"
databricks-cli = "0.285.0"
doctl = "1.149.0"
eza = "0.23.4"
fastfetch = "2.58.0"
fd = "10.3.0"
fzf = "0.67.0"
gh = "2.86.0"
go = "1.25.6"
gron = "0.7.1"
grype = "0.105.0"
hugo = "0.152.2"
hyperfine = "1.20.0"
jc = "1.25.6"
jless = "0.9.0"
jq = "1.8.1"
k9s = "0.50.18"
lnav = "0.13.2"
lua = "5.4.8"
minikube = "1.37.0"
node = "25.4.0"
ollama = "0.13.5"
pandoc = "3.8.3"
pipx = "1.8.0"
poetry = "2.3.1"
python = "3.14.2"
ripgrep = "15.1.0"
rust = "1.93"
sops = "3.11.0"
sqlite = "3.51.2"
starship = "1.24.2"
syft = "1.40.1"
terraform = "1.14.3"
trivy = "0.68.2"
usage = "2.13.1"
uv = "0.9.26"
yarn = "4.12.0"
yazi = "26.1.22"
yq = "4.50.1"
zellij = "0.43.1"
zoxide = "0.9.8"

[settings]
idiomatic_version_file_enable_tools = [
    "go",
    "node",
    "python",
    "terraform",
    "yarn",
]
lockfile = true
experimental = true

[tasks."install-euporie"]
description = "Install TUI Jupyter notebook editor and runner"
run = ["uv tool install euporie"]
