[tools]
"npm:@anthropic-ai/claude-code" = "2.0.72"
"npm:@github/copilot" = "0.0.369"
"npm:opencode-ai" = "1.0.166"
"npm:tree-sitter-cli" = "0.26.3"
"pipx:csvkit" = "2.2.0"
"pipx:tldr" = "3.4.3"
# "cargo:zellij" = "0.43.1"
# imagemagick = "7.1.2-5"
age = "1.2.1"
ansible = "13.1.0"
aws = "2.32.18"
aws-vault = "7.2.0"
azure-cli = "2.81.0"
dagger = "0.19.8"
databricks-cli = "0.280.0"
doctl = "1.148.0"
fzf = "0.67.0"
golang = "1.24.5"
jq = "1.8.1"
k9s = "0.50.16"
lua = "5.4.8"
node = "25.2.1"
pipx = "1.8.0"
poetry = "2.2.1"
python = "3.14.2"
ripgrep = "15.1.0"
rust = "1.92"
sops = "3.11.0"
sqlite = "3.51.1"
starship = "1.24.1"
terraform = "1.14.3"
usage = "2.9.0"
uv = "0.9.18"
yarn = "4.12.0"
yq = "4.50.1"
zellij = "latest"

[settings]
idiomatic_version_file_enable_tools = [
    "go",
    "node",
    "python",
    "terraform",
    "yarn",
]
lockfile = true
experimental = true
